### ISSUE TITLE
SimpleHolder生命周期问题

### ISSUE THREAD

**Issue by bailyzheng** [jarryleo/PagingAdapter#5]
在bindItem中启动了一个timer，想在生命周期结束后取消该timer，我重写了onViewDetach，在onViewDetach取消了timer，但是发现onViewDetach始终未被调用，这是怎么回事？

**Comment by jarryleo** [comment]
onViewDetach 只在条目滑动到不可见时候调用，整个页面不可见不会调用，不建议在 条目中放入计时器，应该在数据bean内存放时间戳，在外部用一个计时器，定时刷新整个列表，在条目内计算当前时间和bean内时间戳的差值，来实现计时。

**Comment by bailyzheng** [comment]
@jarryleo 倒计时任务一个列表中只有前面两三个存在，如果这样在外部放置，然后再刷新感觉很麻烦。而且这样的话SimpleHolder能力被大大限制了，增加一个接口，当recyclerview被销毁时进行回调，这样是否更好点？

**Comment by jarryleo** [comment]
https://github.com/jarryleo/CountDownTextView 你可以试试这个，不需要处理生命周期问题

**Comment by bailyzheng** [comment]
@jarryleo 好的，我试试这个组件。另外我尝试通过传lifecycerOwer到SimpleHolder，然后在SimpleHolder里面进行监听生命周期，但是SimpleHolder通过反射创建的，必须是无参的，感觉这个有一定限制

**Comment by bailyzheng** [comment]
跟SimpleHolder无关，先关闭
